Baseurl = "https://nonumeros.github.io"
LanguageCode = "en-us"
Title = "My New Hugo Site"
Copyright = "&copy; Copyright notice"
theme = "casper"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true

[params]
	subtitle = "a blog"
	author = ""
	authorwebsite ="https://nonumeros.github.io"


