baseurl = "https://nonumeros.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
copyright = "&copy; Copyright notice"
theme = "vienna"


[params]
	subtitle = "a blog"
	author = ""
	authorwebsite ="https://nonumeros.github.io"


